### ISSUE TITLE
New project structure & bootstrap styles applied

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/Products#1]
@chrhol, me and @warpech have reworked Products app.

New project structure and bootstrap styles have been applied. Also some nice GUI features were added. Also I added default layout styles, to make app look nice straight after launch.

Take a look please. You are responsible for the app, so I notify you about the changes.

**Comment by warpech** [comment]
Closing as resolved by [silence procedure](https://en.wikipedia.org/wiki/Silence_procedure) :)
