### ISSUE TITLE
Add a button to cycle through products

### ISSUE THREAD

**Issue by warpech** [Polyjuice/Products#2]
To demonstrate a problem that we have with blinking data change, we need a button to go from a Product to another Product, without leaving ProductPage.html

Let's add <kbd>&lt; Previous Product</kbd>, <kbd>Next Product &gt;</kbd> buttons that cycle through all the prodcuts in the db.

@tomalec, @mtornwall - this is to reproduct the problem you've seen when cycling through recipient pages in @mtornwall's app.

**Comment by mtornwall** [comment]
+1

**Comment by warpech** [comment]
Button created, the problem of blinking pages now tracked in https://github.com/Polyjuice/Polyjuice/issues/58
